# Generated by Django 4.2.6 on 2023-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_catalog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id_accessories', models.AutoField(primary_key=True, serialize=False)),
                ('manufact', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True)),
                ('type', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=20, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'accessories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('name_color', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('surname', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('phone_number', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=12, unique=True)),
                ('email', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EyeDoctor',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('surname', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('patronymic', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=20, null=True)),
                ('post', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('phone_number', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=12, unique=True)),
                ('passport_details', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50, unique=True)),
                ('adress', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=60, null=True)),
            ],
            options={
                'db_table': 'eye_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lenses',
            fields=[
                ('id_lenses', models.AutoField(primary_key=True, serialize=False)),
                ('diopter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('manufact', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'lenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id_order_list', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderr',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_acceptance', models.DateTimeField()),
                ('date_assignment', models.DateTimeField(blank=True, null=True)),
                ('end_price', models.FloatField()),
            ],
            options={
                'db_table': 'orderr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id_prescribtion', models.AutoField(primary_key=True, serialize=False)),
                ('right_diopter', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('left_diopter', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('distance', models.SmallIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rim',
            fields=[
                ('id_rim', models.AutoField(primary_key=True, serialize=False)),
                ('manufact', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'rim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopEmployee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('surname', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('patronymic', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=20, null=True)),
                ('post', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
                ('phone_number', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=12, unique=True)),
                ('passport_details', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50, unique=True)),
                ('adress', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=60)),
            ],
            options={
                'db_table': 'shop_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('meaning_status', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': False},
        ),
    ]
