# Generated by Django 4.2.6 on 2023-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accessories_color_customer_eyedoctor_lenses_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalog',
            table='catalog',
        ),
    ]
